@echo off
@net share admin$ /delete >nul
@net share print$ /delete >nul
@net share q$ /delete >nul
@net share w$ /delete >nul
@net share e$ /delete >nul
@net share r$ /delete >nul
@net share t$ /delete >nul
@net share y$ /delete >nul
@net share u$ /delete >nul
@net share i$ /delete >nul
@net share o$ /delete >nul
@net share p$ /delete >nul
@net share a$ /delete >nul
@net share s$ /delete >nul
@net share d$ /delete >nul
@net share f$ /delete >nul
@net share g$ /delete >nul
@net share h$ /delete >nul
@net share j$ /delete >nul
@net share k$ /delete >nul
@net share l$ /delete >nul
@net share z$ /delete >nul
@net share x$ /delete >nul
@net share c$ /delete >nul
@net share v$ /delete >nul
@net share b$ /delete >nul
@net share n$ /delete >nul
@net share m$ /delete >nul