-- GUID varbinary
DECLARE @GUID_VARBINARY VARBINARY(16) = 0x80BB001E6722B44911E5EC3FE65770F0
SELECT 
	 CONVERT(UNIQUEIDENTIFIER, CONVERT(VARBINARY(64), @GUID_VARBINARY, 1)) [GUID_VARBINARY_v1]
	,CAST(@GUID_VARBINARY AS UNIQUEIDENTIFIER) [GUID_VARBINARY_V2]
	,UPPER(SUBSTRING(SUBSTRING(SYS.FN_SQLVARBASETOSTR(@GUID_VARBINARY),3,32),25,8) + '-' + 
	  SUBSTRING(SUBSTRING(SYS.FN_SQLVARBASETOSTR(@GUID_VARBINARY),3,32),21,4) + '-' + 
	  SUBSTRING(SUBSTRING(SYS.FN_SQLVARBASETOSTR(@GUID_VARBINARY),3,32),17,4) + '-' + 
	  SUBSTRING(SUBSTRING(SYS.FN_SQLVARBASETOSTR(@GUID_VARBINARY),3,32),1,4) + '-' + 
	  SUBSTRING(SUBSTRING(SYS.FN_SQLVARBASETOSTR(@GUID_VARBINARY),3,32),5,12)) [GUID_VARBINARY_V3]
