------------------------------------------------------------------------------------------------------------------------
-- DEAD LOCKS
------------------------------------------------------------------------------------------------------------------------
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
DECLARE @IS_KILL BIT = 0;
DECLARE @IS_DM_EXEC_REQUESTS BIT = 1;
DECLARE @IS_SELECT_1 BIT = 0;
DECLARE @IS_SELECT_2 BIT = 0;
DECLARE @IS_SP_WHO2 BIT = 1;
------------------------------------------------------------------------------------------------------------------------
IF (@IS_KILL = 1) BEGIN
	PRINT N'[i] @IS_KILL IS ACTIVE';
	KILL 55; -- PROC_ID
END;
------------------------------------------------------------------------------------------------------------------------
IF (@IS_DM_EXEC_REQUESTS = 1) BEGIN
	PRINT N'[i] @IS_DM_EXEC_REQUESTS IS ACTIVE';
	SELECT * -- BLOCKING_SESSION_ID
	FROM [SYS].[DM_EXEC_REQUESTS]
	WHERE BLOCKING_SESSION_ID <> 0
END;
------------------------------------------------------------------------------------------------------------------------
IF (@IS_SELECT_1 = 1) BEGIN
	PRINT N'[i] @IS_SELECT_1 IS ACTIVE';
	SELECT
		DB.NAME DBNAME,
		TL.REQUEST_SESSION_ID,
		WT.BLOCKING_SESSION_ID,
		OBJECT_NAME(P.OBJECT_ID) BLOCKEDOBJECTNAME,
		TL.RESOURCE_TYPE,
		H1.TEXT AS REQUESTINGTEXT,
		H2.TEXT AS BLOCKINGTEST,
		TL.REQUEST_MODE
	FROM [SYS].[DM_TRAN_LOCKS] [TL]
	INNER JOIN [SYS].[DATABASES] [DB] ON [DB].[DATABASE_ID] = [TL].[RESOURCE_DATABASE_ID]
	INNER JOIN [SYS].[DM_OS_WAITING_TASKS] [WT] ON [TL].[LOCK_OWNER_ADDRESS] = [WT].[RESOURCE_ADDRESS]
	INNER JOIN SYS.PARTITIONS AS P ON P.HOBT_ID = TL.RESOURCE_ASSOCIATED_ENTITY_ID
	INNER JOIN SYS.DM_EXEC_CONNECTIONS EC1 ON EC1.SESSION_ID = TL.REQUEST_SESSION_ID
	INNER JOIN SYS.DM_EXEC_CONNECTIONS EC2 ON EC2.SESSION_ID = WT.BLOCKING_SESSION_ID
	CROSS APPLY SYS.DM_EXEC_SQL_TEXT(EC1.MOST_RECENT_SQL_HANDLE) AS H1
	CROSS APPLY SYS.DM_EXEC_SQL_TEXT(EC2.MOST_RECENT_SQL_HANDLE) AS H2
END;
------------------------------------------------------------------------------------------------------------------------
IF (@IS_SELECT_2 = 1) BEGIN
	PRINT N'[i] @IS_SELECT_2 IS ACTIVE';
	SELECT DB.NAME DBNAME,
		TL.REQUEST_SESSION_ID AS REQSESSIONID, ESR.HOST_NAME AS REQHOST, ESR.PROGRAM_NAME AS REQPROGRAM, ESR.CLIENT_INTERFACE_NAME AS REQCLIENT, ESR.LOGIN_NAME AS REQLOGIN,
		WT.BLOCKING_SESSION_ID AS BLKSESSIONID, ESB.HOST_NAME AS BLKHOST, ESB.PROGRAM_NAME AS BLKPROGRAM, ESB.CLIENT_INTERFACE_NAME AS BLKCLIENT, ESB.LOGIN_NAME AS BLKLOGIN,
		OBJECT_NAME(P.OBJECT_ID) BLOCKEDOBJECTNAME,
		TL.RESOURCE_TYPE,
		H1.TEXT AS REQUESTINGTEXT,
		H2.TEXT AS BLOCKINGTEST,
		TL.REQUEST_MODE
	FROM SYS.DM_TRAN_LOCKS AS TL
	INNER JOIN SYS.DATABASES DB ON DB.DATABASE_ID = TL.RESOURCE_DATABASE_ID
	INNER JOIN SYS.DM_OS_WAITING_TASKS AS WT ON TL.LOCK_OWNER_ADDRESS = WT.RESOURCE_ADDRESS
	INNER JOIN SYS.PARTITIONS AS P ON P.HOBT_ID = TL.RESOURCE_ASSOCIATED_ENTITY_ID
	INNER JOIN SYS.DM_EXEC_CONNECTIONS EC1 ON EC1.SESSION_ID = TL.REQUEST_SESSION_ID
	INNER JOIN SYS.DM_EXEC_CONNECTIONS EC2 ON EC2.SESSION_ID = WT.BLOCKING_SESSION_ID
	JOIN SYS.DM_EXEC_SESSIONS ESR ON ESR.SESSION_ID = TL.REQUEST_SESSION_ID
	JOIN SYS.DM_EXEC_SESSIONS ESB ON ESB.SESSION_ID = WT.BLOCKING_SESSION_ID
	CROSS APPLY SYS.DM_EXEC_SQL_TEXT(EC1.MOST_RECENT_SQL_HANDLE) AS H1
	CROSS APPLY SYS.DM_EXEC_SQL_TEXT(EC2.MOST_RECENT_SQL_HANDLE) AS H2
END;
------------------------------------------------------------------------------------------------------------------------
IF (@IS_SP_WHO2 = 1) BEGIN
	PRINT N'[i] @IS_SP_WHO2 IS ACTIVE';
	USE [MASTER];
	EXEC SP_WHO2;
END;
------------------------------------------------------------------------------------------------------------------------
